### ISSUE TITLE
DDA Rough Draft - Data Storage Design

### ISSUE THREAD

**Issue by msmith406** [mitelinko/heroes-manual#27]
[Rough Draft](https://docs.google.com/document/d/179-MGX601ogFbiQYt4Djd10xnhekEGEDBFqxXZR_wQE/edit?usp=sharing)
[Assignment Description](https://files.t-square.gatech.edu/access/content/group/gtc-ebbf-3491-53f2-b549-4382e5367f77/Detailed%20Design/Detailed%20Design%20Assignment%20Spring%202018.pdf)

● Introduce this section by providing your reader with enough context to understand
the information that follows.
● For database use: An ER diagram is provided. Relationships between tables and
cardinality constraints are shown. Tables are appropriately normalized. PK/FK
relationships are shown if needed.
● For file use: Format is documented if non-standard. Otherwise, a standard format is
chosen.
● For data exchange: Format is documented.

Due: 2/25

Note: This section is not very applicable for database use BUT it is applicable for describing the types of files we use and data exchange - like the pdf and qr code for the safety plan

**Comment by colbs255** [comment]
PDF/QR code stuff
