### ISSUE TITLE
Create a Safety Plan

### ISSUE THREAD

**Issue by msmith406** [mitelinko/heroes-manual#8]
As a healthcare professional, I want to be able to help a domestic violence victim create a safety plan.

Need to decide what is outputted --> Something to print? etc

**Comment by NikSethi** [comment]
Subtasks:
[ ] Brainstorm possible flows
[ ] Sketch out
[ ] Mockups
[ ] Dev

**Comment by NikSethi** [comment]
### Subtasks:
- [ ] Brainstorm possible flows
- [ ] Sketch out
- [ ] Mockups
- [ ] Dev
